package org.binas.ws.cli;

import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;

import javax.xml.ws.AsyncHandler;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Response;

import org.binas.ws.TestInitResponse;
import org.binas.ws.ActivateUserResponse;
import org.binas.ws.AlreadyHasBina_Exception;
import org.binas.ws.BadInit_Exception;
import org.binas.ws.BinasPortType;
import org.binas.ws.BinasService;
import org.binas.ws.CoordinatesView;
import org.binas.ws.EmailExists_Exception;
import org.binas.ws.FullStation_Exception;
import org.binas.ws.GetCreditResponse;
import org.binas.ws.GetInfoStationResponse;
import org.binas.ws.InvalidEmail_Exception;
import org.binas.ws.InvalidStation_Exception;
import org.binas.ws.ListStationsResponse;
import org.binas.ws.NoBinaAvail_Exception;
import org.binas.ws.NoBinaRented_Exception;
import org.binas.ws.NoCredit_Exception;
import org.binas.ws.RentBinaResponse;
import org.binas.ws.ReturnBinaResponse;
import org.binas.ws.StationView;
import org.binas.ws.TestClearResponse;
import org.binas.ws.TestInitStationResponse;
import org.binas.ws.TestPingResponse;
import org.binas.ws.UserNotExists_Exception;
import org.binas.ws.UserView;

import pt.ulisboa.tecnico.sdis.ws.uddi.UDDINaming;


/**
 * Client.
 *
 * Adds easier endpoint address configuration and 
 * UDDI lookup capability to the PortType generated by wsimport.
 */
public class BinasClient implements BinasPortType {

	
	
	
    /** WS service */
    BinasService service = null;

    /** WS port (port type is the interface, port is the implementation) */
    BinasPortType port = null;

    /** UDDI server URL */
    private String uddiURL = null;

    /** WS name */
    private String wsName = null;

    /** WS endpoint address */
    private String wsURL = null; // default value is defined inside WSDL

    public String getWsURL() {
        return wsURL;
    }

    /** output option **/
    private boolean verbose = false;

    public boolean isVerbose() {
        return verbose;
    }

    public void setVerbose(boolean verbose) {
        this.verbose = verbose;
    }

    /** constructor with provided web service URL */
    public BinasClient(String wsURL) throws BinasClientException {
        this.wsURL = wsURL;
        createStub();
    }

    /** constructor with provided UDDI location and name */
    public BinasClient(String uddiURL, String wsName) throws BinasClientException {
        this.uddiURL = uddiURL;
        this.wsName = wsName;
        uddiLookup();
        createStub();
    }

    /** UDDI lookup */
    private void uddiLookup() throws BinasClientException {
        try {
            if (verbose)
                System.out.printf("Contacting UDDI at %s%n", uddiURL);
            UDDINaming uddiNaming = new UDDINaming(uddiURL);

            if (verbose)
                System.out.printf("Looking for '%s'%n", wsName);
            wsURL = uddiNaming.lookup(wsName);

        } catch (Exception e) {
            String msg = String.format("Client failed lookup on UDDI at %s!",
                    uddiURL);
            throw new BinasClientException(msg, e);
        }

        if (wsURL == null) {
            String msg = String.format(
                    "Service with name %s not found on UDDI at %s", wsName,
                    uddiURL);
            throw new BinasClientException(msg);
        }
    }

    /** Stub creation and configuration */
    private void createStub() {
        if (verbose)
            System.out.println("Creating stub ...");
        service = new BinasService();
        port = service.getBinasPort();

        if (wsURL != null) {
            if (verbose)
                System.out.println("Setting endpoint address ...");
            BindingProvider bindingProvider = (BindingProvider) port;
            Map<String, Object> requestContext = bindingProvider
                    .getRequestContext();
            requestContext.put(ENDPOINT_ADDRESS_PROPERTY, wsURL);
        }
    }

    
	@Override
	public UserView activateUser(String email) throws EmailExists_Exception, InvalidEmail_Exception {
		return port.activateUser(email);
	}

	@Override
	public StationView getInfoStation(String stationId) throws InvalidStation_Exception {
		return port.getInfoStation(stationId);
	}

	@Override
	public List<StationView> listStations(Integer numberOfStations, CoordinatesView coordinates) {
		return port.listStations(numberOfStations,coordinates);
	}

	@Override
	public void rentBina(String stationId, String email) throws AlreadyHasBina_Exception, InvalidStation_Exception,
			NoBinaAvail_Exception, NoCredit_Exception, UserNotExists_Exception {
		
		port.rentBina(stationId,email);
	}

	@Override
	public void returnBina(String stationId, String email)
			throws FullStation_Exception, InvalidStation_Exception, NoBinaRented_Exception, UserNotExists_Exception {
		port.returnBina(stationId,email);
	}


	
	@Override
	public int getCredit(String email) throws UserNotExists_Exception {
		return port.getCredit(email);
	}

	@Override
	public String testPing(String inputMessage) {
		return port.testPing(inputMessage);
	}

	@Override
	public void testClear() {
		port.testClear();
	}

	@Override
	public void testInitStation(String stationId, int x, int y, int capacity, int returnPrize)
			throws BadInit_Exception {
		port.testInitStation(stationId, x, y, capacity, returnPrize);
	}
	
	@Override
	public Response<TestInitStationResponse>  testInitStationAsync(String stationId, int x, int y, int capacity, int returnPrize) {
		return port.testInitStationAsync(stationId, x, y, capacity, returnPrize);
	}
	
	@Override
	public Future<?> testInitStationAsync(String stationId, int x, int y, int capacity, int returnPrize,AsyncHandler<TestInitStationResponse> asyncHandler) {
		return port.testInitStationAsync(stationId, x, y, capacity, returnPrize, asyncHandler);
	}

	@Override
	public void testInit(int userInitialPoints) throws BadInit_Exception {
		port.testInit(userInitialPoints);
	}
	
	@Override
	public Response<TestInitResponse> testInitAsync(int userInitialPoints) {
		return port.testInitAsync(userInitialPoints);
	}
	
	@Override
	public Future<?> testInitAsync(int userInitialPoints,AsyncHandler<TestInitResponse> asyncHandler) {
		return port.testInitAsync(userInitialPoints, asyncHandler);
	}

	@Override
	public Response<ListStationsResponse> listStationsAsync(Integer numberOfStations, CoordinatesView coordinates) {
		return port.listStationsAsync(numberOfStations,coordinates);
	}

	@Override
	public Future<?> listStationsAsync(Integer numberOfStations, CoordinatesView coordinates,
			AsyncHandler<ListStationsResponse> asyncHandler) {
		return port.listStationsAsync(numberOfStations,coordinates);
	}

	@Override
	public Response<GetInfoStationResponse> getInfoStationAsync(String stationId) {
		return port.getInfoStationAsync(stationId);
	}

	@Override
	public Future<?> getInfoStationAsync(String stationId, AsyncHandler<GetInfoStationResponse> asyncHandler) {
		return port.getInfoStationAsync(stationId, asyncHandler);
	}

	@Override
	public Response<GetCreditResponse> getCreditAsync(String email) {
		return port.getCreditAsync(email);
	}

	@Override
	public Future<?> getCreditAsync(String email, AsyncHandler<GetCreditResponse> asyncHandler) {
		return port.getCreditAsync(email, asyncHandler);
	}

	@Override
	public Response<ActivateUserResponse> activateUserAsync(String email) {
		return port.activateUserAsync(email);
	}

	@Override
	public Future<?> activateUserAsync(String email, AsyncHandler<ActivateUserResponse> asyncHandler) {
		return port.activateUserAsync(email, asyncHandler);
	}

	@Override
	public Response<RentBinaResponse> rentBinaAsync(String stationId, String email) {
		return port.rentBinaAsync(stationId, email);
	}

	@Override
	public Future<?> rentBinaAsync(String stationId, String email, AsyncHandler<RentBinaResponse> asyncHandler) {
		return port.rentBinaAsync(stationId, email, asyncHandler);
	}

	@Override
	public Response<ReturnBinaResponse> returnBinaAsync(String stationId, String email) {
		return port.returnBinaAsync(stationId, email);
	}

	@Override
	public Future<?> returnBinaAsync(String stationId, String email, AsyncHandler<ReturnBinaResponse> asyncHandler) {
		return port.returnBinaAsync(stationId, email, asyncHandler);
	}

	@Override
	public Response<TestPingResponse> testPingAsync(String inputMessage) {
		return port.testPingAsync(inputMessage);
	}

	@Override
	public Future<?> testPingAsync(String inputMessage, AsyncHandler<TestPingResponse> asyncHandler) {
		return port.testPingAsync(inputMessage, asyncHandler);
	}

	@Override
	public Response<TestClearResponse> testClearAsync() {
		return port.testClearAsync();
	}

	@Override
	public Future<?> testClearAsync(AsyncHandler<TestClearResponse> asyncHandler) {
		return port.testClearAsync(asyncHandler);
	}
	
	

	

}   